countries = [
    "Afghanistan", "South Africa", "Albania", "Germany", "Andorra", "Angola", "Antigua and Barbuda",
    "Saudi Arabia", "Algeria", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
    "Bahamas", "Bangladesh", "Barbados", "Bahrain", "Belgium", "Belize", "Benin", "Belarus",
    "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso",
    "Burundi", "Bhutan", "Cape Verde", "Cameroon", "Cambodia", "Canada", "Qatar", "Kazakhstan",
    "Chad", "Chile", "China", "Cyprus", "Colombia", "Comoros", "Republic of the Congo",
    "Democratic Republic of the Congo", "North Korea", "South Korea", "Ivory Coast", "Costa Rica",
    "Croatia", "Cuba", "Denmark", "Djibouti", "Dominica", "Egypt", "El Salvador",
    "United Arab Emirates", "Ecuador", "Eritrea", "Slovakia", "Slovenia", "Spain",
    "United States", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Philippines", "Finland",
    "France", "Gabon", "Gambia", "Ghana", "Georgia", "Grenada", "Greece", "Guatemala", "Guyana",
    "Guinea", "Guinea-Bissau", "Equatorial Guinea", "Haiti", "Netherlands", "Honduras", "Hungary",
    "Yemen", "Marshall Islands", "Solomon Islands", "India", "Indonesia", "Iran", "Iraq", "Ireland",
    "Iceland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kiribati", "Kosovo", "Kuwait",
    "Laos", "Lesotho", "Latvia", "Lebanon", "Liberia", "Libya", "Liechtenstein", "Lithuania",
    "Luxembourg", "North Macedonia", "Madagascar", "Malaysia", "Malawi", "Maldives", "Mali",
    "Malta", "Morocco", "Mauritius", "Mauritania", "Mexico", "Myanmar", "Micronesia", "Mozambique",
    "Moldova", "Monaco", "Mongolia", "Montenegro", "Namibia", "Nauru", "Nepal", "Nicaragua",
    "Niger", "Nigeria", "Norway", "New Zealand", "Oman", "Palau", "Palestine", "Panama",
    "Papua New Guinea", "Pakistan", "Paraguay", "Peru", "Poland", "Portugal", "Kenya",
    "Kyrgyzstan", "United Kingdom", "Central African Republic", "Dominican Republic",
    "Czech Republic", "Romania", "Rwanda", "Russia", "Western Sahara", "Samoa", "San Marino",
    "Saint Lucia", "Saint Kitts and Nevis", "São Tomé and Príncipe", "Saint Vincent and the Grenadines",
    "Seychelles", "Senegal", "Sierra Leone", "Serbia", "Singapore", "Syria", "Somalia", "Sri Lanka",
    "Sudan", "South Sudan", "Sweden", "Switzerland", "Suriname", "Thailand", "Taiwan", "Tajikistan",
    "Tanzania", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkmenistan",
    "Turkey", "Tuvalu", "Ukraine", "Uganda", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican",
    "Venezuela", "Vietnam", "Zambia", "Zimbabwe"
]

languages = [
    "Arabic",
    "Bengali",
    "English",
    "Hindi",
    "Japanese",
    "Mandarin Chinese",
    "Pashto",
    "Persian (Farsi)",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Russian",
    "Spanish",
    "Tagalog (Filipino)",
    "Turkish"
]
